theme: WIP catppuccin

diff --git a/.zsh/functions/rebuild_symlinks b/.zsh/functions/rebuild_symlinks
--- a/.zsh/functions/rebuild_symlinks
+++ b/.zsh/functions/rebuild_symlinks
@@ -11,27 +11,35 @@ _rebuild_symlink() {
   if [[ -f "$src" ]]; then
     mkdir -p "${dest:h}"
     ln -sf "$src" "$dest"
-    echo "INFO: created symlink: $dest -> $src"
+    echo "[INFO] created symlink: $dest -> $src"
   else
-    echo "ERROR: missing file: $src" >&2
+    echo "[ERROR] missing file: $src" >&2
     (( num_errors++ ))
   fi
 }
 
+_replace_file_from_url() {
+  local dest_file="$1"
+  local src_url="$2"
+  local tmp_file
+  tmp_file="$(mktemp)"
 
-# --- bat theme ---
-_rebuild_symlink \
-  ~/.local/share/nvim/site/pack/core/opt/tokyonight.nvim/extras/sublime/tokyonight_night.tmTheme \
-  ~/.config/bat/themes/custom.tmTheme
+  echo "[INFO] downloading $src_url"
+  if curl -fsSL -o "$tmp_file" "$src_url"; then
+    if [[ -L "$dest_file" ]]; then
+      rm -f "$dest_file"
+    fi
+    mv "$tmp_file" "$dest_file"
+    echo "[INFO] replaced $dest_file with content from $src_url"
+  else
+    echo "[ERROR] download failed: $src_url" >&2
+    rm -f "$tmp_file"
+    (( num_errors++ ))
+  fi
+}
 
+_replace_file_from_url ~/.config/eza/theme.yml 'https://raw.githubusercontent.com/eza-community/eza-themes/main/themes/catppuccin-mocha.yml'
 
-# --- eza theme ---
-_rebuild_symlink \
-  ~/.local/share/nvim/site/pack/core/opt/tokyonight.nvim/extras/eza/tokyonight_night.yml \
-  ~/.config/eza/theme.yml
-
-
-# ---
 if (( num_errors > 0 )); then
   return 1
 fi
